### ISSUE TITLE
"test_index_file_endianness_compatibility" isn't really about endianness

### ISSUE THREAD

**Issue by itamarst** [marcin-krystianc/PalletJack#24]
I'm not sure how you would get access to a big-endian computer, unless you have IBM Power machines somewhere? A better name is more "golden master"/"approval test" or something like that, if I understand this correctly.

**Comment by marcin-krystianc** [comment]
> I'm not sure how you would get access to a big-endian computer, unless you have IBM Power machines somewhere? A better name is more "golden master"/"approval test" or something like that, if I understand this correctly.

I agree wit your suggestions. FYI, I almost got the test working (see https://github.com/marcin-krystianc/PalletJack/blob/dev-20240104-bigendian/.github/workflows/python-ci.yml#L16-L44) but had some troubles installing `pyarrow` from source.
I think with some more effort it is actually doable, but I decided to abandon the idea for now.
